import React, { useState, useEffect, useRef } from "react";
import {
  CheckCircle,
  Lock,
  FileText,
  Clock,
  AlertCircle
} from "lucide-react";
import axios from "axios";

export default function ApplicationGuidance() {
  const [profile, setProfile] = useState(null);
  const [shortlisted, setShortlisted] = useState([]);
  const [selectedUni, setSelectedUni] = useState(null);
  const [tasks, setTasks] = useState([]);
  const [loading, setLoading] = useState(true);
  const [lockedUniversity, setLockedUniversity] = useState(null);
  const [updatingTaskId, setUpdatingTaskId] = useState(null);
  const [showCompletionModal, setShowCompletionModal] = useState(false);


  // 🔐 Prevent duplicate AI calls
  const autoGeneratedRef = useRef({});

  // 🔁 Refresh profile
  const refreshProfile = async () => {
    const token = localStorage.getItem("token");
    const res = await axios.get(
      "http://localhost:5000/auth/me",
      { headers: { Authorization: `Bearer ${token}` } }
    );
    setProfile(res.data.profile);
    return res.data.profile;
  };

  // 🚀 SINGLE SOURCE OF TRUTH (DB → AI → UI)
  const loadUniversityTasksAuto = async (uni, userProfile) => {
    if (!uni || !userProfile) return;

    setSelectedUni(uni);
    setTasks([]);
    setLoading(true);

    // 1️⃣ DB FIRST
    const existing = (userProfile.applicationTasks || []).find(
      t => t.universityName === uni.name
    );

    if (existing) {
      setTasks(existing.tasks);
      setLoading(false);
      return;
    }

    // 2️⃣ PREVENT DUPLICATE AI CALLS
    if (autoGeneratedRef.current[uni.name]) {
      setLoading(false);
      return;
    }

    autoGeneratedRef.current[uni.name] = true;

    // 3️⃣ AI GENERATION (ONCE)
    try {
      const token = localStorage.getItem("token");

      const res = await axios.post(
        "http://localhost:5000/ai/generate-tasks",
        { universityName: uni.name },
        { headers: { Authorization: `Bearer ${token}` } }
      );

      setTasks(res.data.tasks);
      await refreshProfile();
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  // 🔥 INIT ON PAGE LOAD
  useEffect(() => {
    const init = async () => {
      try {
        const token = localStorage.getItem("token");
        const res = await axios.get(
          "http://localhost:5000/auth/me",
          { headers: { Authorization: `Bearer ${token}` } }
        );

        const userProfile = res.data.profile;
        setProfile(userProfile);

        const lockedUnis = (userProfile.shortlistedUniversities || []).filter(
          u => u.locked
        );

        setShortlisted(lockedUnis);
        setLockedUniversity(lockedUnis[0] || null);

        if (lockedUnis.length > 0) {
          await loadUniversityTasksAuto(lockedUnis[0], userProfile);
        }

      } catch (err) {
        console.error(err);
      }
    };

    init();
  }, []);



  useEffect(() => {
    if (!selectedUni || tasks.length === 0) return;

    const allCompleted = tasks.every(t => t.completed);
    if (!allCompleted) return;

    const key = `app_complete_shown_${selectedUni.name}`;
    const alreadyShown = localStorage.getItem(key);

    if (!alreadyShown) {
      setShowCompletionModal(true);
      localStorage.setItem(key, "true");
    }
  }, [tasks, selectedUni]);



  // 👆 University tab click
  const handleSelectUniversity = async (uni) => {
    if (!profile) return;
    await loadUniversityTasksAuto(uni, profile);
  };

  // ✅ Toggle task completion
  const toggleTask = async (taskId) => {
    setUpdatingTaskId(taskId);

    setTasks(prev =>
      prev.map(t =>
        t.id === taskId ? { ...t, completed: !t.completed } : t
      )
    );

    try {
      const token = localStorage.getItem("token");
      await axios.post(
        "http://localhost:5000/auth/tasks/toggle",
        { universityName: selectedUni.name, taskId },
        { headers: { Authorization: `Bearer ${token}` } }
      );
    } catch (err) {
      console.error(err);
    } finally {
      setUpdatingTaskId(null);
    }
  };

  // 📊 Progress helpers
  const countByGroup = (group) =>
    tasks.filter(t => t.group === group).length;

  const completedByGroup = (group) =>
    tasks.filter(t => t.group === group && t.completed).length;

  const totalTasks = tasks.length;
  const completedTasks = tasks.filter(t => t.completed).length;

  const progressPercent =
    totalTasks === 0 ? 0 : Math.round((completedTasks / totalTasks) * 100);

  return (
    <div className="px-4 py-20 md:px-8 md:py-8 bg-[#FBFAF8] min-h-screen">

      {/* HEADER */}
      <div className="mb-10">
        <h1 className="text-2xl md:text-3xl font-bold text-gray-900">
          Application Guidance</h1>
        <p className="text-gray-500 mt-1">
          Your personalized application tasks and timeline for locked universities
        </p>
      </div>

      {/* COMMITTED */}
      <div className="mb-10">
        <div className="flex items-center gap-2 mb-4 text-lg font-medium">
          <Lock className="text-blue-600" size={18} />
          Your Committed Universities
        </div>

        <div className="bg-white rounded-2xl shadow border-l-4 border-green-500 p-4">
          {lockedUniversity && (
            <div className="flex gap-2 md:gap-3 overflow-x-auto scrollbar-hide">
              {shortlisted.map(uni => (
                <button
                  key={uni.name}
                  onClick={() => handleSelectUniversity(uni)}
                  className={`px-4 py-2 w-62 rounded-xl text-sm font-medium
                    ${selectedUni?.name === uni.name
                      ? "bg-blue-600 text-white"
                      : "bg-gray-100 text-gray-700 hover:bg-gray-200"
                    }`}
                >
                  {uni.name}
                </button>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* MAIN GRID */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 md:gap-10">

        {/* TASKS */}
        <div className="md:col-span-2 space-y-6 md:space-y-8">
          <div className="flex items-center gap-2 text-xl font-medium">
            <AlertCircle className="text-blue-600" size={20} />
            Application Tasks
          </div>

          {loading && (
            <p className="text-center text-gray-500">
              AI is preparing your application plan and tasks…
            </p>
          )}

          {["Documents", "Exams", "Forms"].map(group => {
            const groupTasks = tasks.filter(t => t.group === group);
            if (!groupTasks.length) return null;

            return (
              <TaskGroup
                key={group}
                title={group}
                icon={group === "Documents"
                  ? <FileText size={18} />
                  : <Clock size={18} />}
              >
                {groupTasks.map(task => (
                  <Task
                    key={task.id}
                    {...task}
                    universityName={selectedUni?.name}   // ✅ PASS IT HERE
                    loading={updatingTaskId === task.id}
                    onToggle={() => toggleTask(task.id)}
                  />
                ))}
              </TaskGroup>
            );
          })}
        </div>

        {/* SIDEBAR */}
        <div className="space-y-6 md:space-y-8">
          <p className="font-semibold text-lg">Progress Summary</p>

          <div className="bg-white rounded-2xl shadow p-4 md:p-6">
            <div className="mb-4 text-sm">
              {completedTasks}/{totalTasks}
            </div>

            <div className="w-full h-2 bg-gray-100 rounded-full">
              <div
                className="h-2 bg-blue-600 rounded-full transition-all"
                style={{ width: `${progressPercent}%` }}
              />
            </div>

            <div className="mt-4 space-y-2 text-sm">
              <ProgressRow label="Documents" value={`${completedByGroup("Documents")}/${countByGroup("Documents")}`} />
              <ProgressRow label="Exams" value={`${completedByGroup("Exams")}/${countByGroup("Exams")}`} />
              <ProgressRow label="Forms" value={`${completedByGroup("Forms")}/${countByGroup("Forms")}`} />
            </div>
          </div>

          <p className="font-semibold text-lg mb-4">Key Documents</p>

          <div className="bg-white rounded-2xl shadow-[0_6px_18px_rgba(0,0,0,0.06)]  p-4 md:p-6">
            <ul className="space-y-3 text-sm text-gray-700">
              <li className="flex items-center gap-2">📄 Statement of Purpose (SOP)</li>
              <li className="flex items-center gap-2">📄 Letters of Recommendation</li>
              <li className="flex items-center gap-2">📄 Academic Transcripts</li>
              <li className="flex items-center gap-2">📄 Resume / CV</li>
              <li className="flex items-center gap-2">📄 English Proficiency Score</li>
              <li className="flex items-center gap-2">📄 Passport Copy</li>
            </ul>
          </div>

        </div>
      </div>

      {showCompletionModal && selectedUni && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm">

          <div className="bg-white w-[95%] md:max-w-lg max-h-[90vh] overflow-y-auto rounded-3xl p-5 md:p-8 shadow-2xl text-center relative">

            {/* 🎉 ICON */}
            <div className="mx-auto w-16 h-16 rounded-full bg-green-500 flex items-center justify-center mb-4">
              <CheckCircle size={32} className="text-white" />
            </div>

            <h2 className="text-2xl font-bold text-gray-900 mb-2">
              Application Ready 🎉
            </h2>

            <p className="text-gray-600 mb-6">
              You’ve successfully completed all application tasks for
            </p>

            <p className="text-lg font-semibold text-blue-600 mb-6">
              {selectedUni.name}
            </p>

            {/* PROFILE SNAPSHOT */}
            <div className="bg-gray-50 rounded-xl p-4  text-sm text-gray-700 mb-6">
              <p className="mb-2"><strong>Degree:</strong> {profile?.intendedDegree || "—"}</p>
              <p className="mb-2"><strong>Field:</strong> {profile?.fieldOfStudy || "—"}</p>
              <p className="mb-2"><strong>Target Intake:</strong> {profile?.targetIntake || "—"}</p>
            </div>

            {/* MOTIVATION */}
            <p className="text-gray-600 mb-6">
              You’re fully prepared to apply.
              Best of luck with your application - go crush it 🚀
            </p>

            {/* ACTIONS */}
            <div className="flex gap-4 justify-center">
              <button
                onClick={() => setShowCompletionModal(false)}
                className="px-6 py-3 rounded-xl border text-gray-600 hover:bg-gray-100"
              >
                Close
              </button>

              <button
                onClick={() => {
                  const applyUrl =
                    selectedUni.portalUrl || selectedUni.website;

                  if (!applyUrl) {
                    alert("Application portal not available");
                    return;
                  }

                  window.open(applyUrl, "_blank");
                }}
                className="px-6 py-3 rounded-xl bg-gradient-to-r from-blue-600 to-purple-600 text-white font-medium"
              >
                Apply Now
              </button>
            </div>

          </div>
        </div>
      )}

    </div>
  );
}

function detectExamType(title = "") {
  const t = title.toLowerCase();

  if (t.includes("ielts")) return "ielts";
  if (t.includes("toefl")) return "toefl";
  if (t.includes("gre")) return "gre";
  if (t.includes("gmat")) return "gmat";

  return null;
}


/* ---------- Components ---------- */

function TaskGroup({ title, icon, children }) {
  return (
    <div className="bg-white rounded-2xl shadow p-4 md:p-6">
      <div className="flex items-center gap-2 font-semibold mb-4">
        {icon}
        {title}
      </div>
      <div className="space-y-4">{children}</div>
    </div>
  );
}

function Task({ title, desc, priority, completed, onToggle, loading, universityName }) {
  return (
    <div
      onClick={!loading ? onToggle : undefined}
      className={`flex flex-col md:flex-row md:justify-between gap-4 cursor-pointer transition
        ${loading ? "opacity-60" : "hover:bg-gray-50"}`}
    >
      <div className="flex gap-4">
        <div className={`w-5 h-5 rounded-full border flex items-center justify-center
          ${completed ? "bg-green-500 border-green-500" : "border-gray-400"}
          ${loading ? "animate-pulse" : ""}`}
        >
          {completed && <CheckCircle size={14} className="text-white" />}
        </div>

        <div className="w-full md:w-[80%]">
          <p className={`font-medium ${completed && "line-through  text-gray-400"}`}>
            {title}
          </p>
          <p className="text-sm text-gray-500">{desc}</p>
        </div>
      </div>

      <div className="flex gap-3 md:gap-4 items-start md:items-center">
        <span className={`px-3 py-1 h-6 rounded-full text-xs font-medium
        ${priority === "high"
            ? "bg-red-100 text-red-600"
            : "bg-orange-100 text-orange-600"}`}
        >
          {priority}
        </span>

        <button
          onClick={(e) => {
            e.stopPropagation(); // prevent task toggle

            const examType = detectExamType(title);

            if (examType) {
              // 🎙️ EXAM FLOW (NO DB)
              localStorage.setItem(
                "ai_exam_context",
                JSON.stringify({
                  examType,
                  title,
                  university: universityName
                })
              );

              window.location.href = `/ai-exam/${examType}`;
            } else {
              // 🤖 NORMAL AI COUNSELLOR
              localStorage.setItem(
                "ai_task_context",
                JSON.stringify({
                  title,
                  desc,
                  university: universityName
                })
              );

              window.location.href = "/ai-counsellor";
            }
          }}
          className="px-3 py-1 text-xs h-6 w-20 flex rounded-full
             bg-purple-100 text-purple-700 hover:bg-purple-200"
        >
          🤖 Ask AI
        </button>

      </div>

    </div>
  );
}

function ProgressRow({ label, value }) {
  return (
    <div className="flex justify-between text-gray-600">
      <span>{label}</span>
      <span>{value}</span>
    </div>
  );
}
